---
- name:
  hosts: localhost
  gather_facts: False
  tasks:
    - set_fact:
        region: us-east-1
        stack_name: lambda-cdn-image-resize-origin-response
        cfn_template_ansible: ../templates/cfn-cdn-image-resize.yml

    - set_fact:
        lambda_language: nodejs14.x
        lambda_entry: index.js
        lambda_timeout: 30
        lambda_memory_size: 256
        lambda_name: func-cdn-image-resize-origin-response
        alarm_sns_stack_name: sns-alarm

    - set_fact:
        src_path: ../src/image-resize/origin-response
        archive_dir: /tmp/lambda/image-resize
        script: |
        zip_name: "{{ lambda_name }}.zip"

    - set_fact:
        s3_bucket: kfc.internal.virginia
        s3_object_key: "{{ zip_name }}"
        s3_object_version: ''

    - include_tasks: ../tasks/stack.yml
