---
AWSTemplateFormatVersion: "2010-09-09"
Description: iam users

Parameters:
  GourpsStackName:
    Type: String
    Default: iam-groups
    Description: groups stack name

  PoliciesStackName:
    Type: String
    Default: iam-policies
    Description: policies stack name

Resources:
  # ----------------------- Administrator -----------------------
  ZhengJianFeng:
    Type: AWS::IAM::User
    Properties:
      UserName: codiy
      LoginProfile:
        Password: WhatTheFuck123
        PasswordResetRequired: true
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /
  # ----------------------- Rclone -----------------------
  # @link https://docs.aws.amazon.com/zh_cn/AmazonS3/latest/userguide/example-policies-s3.html
  Rclone:
    Type: AWS::IAM::User
    Properties:
      UserName: rclone
      Path: /
      Policies:
        - PolicyName: KfcRclonePolicy
          PolicyDocument:
            Statement:
            - Sid: AllowListBuckets
              Effect: Allow
              Action:
                - 's3:ListAllMyBuckets'
              Resource: 'arn:aws:s3:::*'
            - Sid: AllowManageBucketObjects
              Effect: Allow
              Action:
                - 's3:ListBucket'
                - 's3:GetBucketLocation'
                - 's3:GetObject'
                - 's3:GetObjectAcl'
                - 's3:GetObjectVersion'
                - 's3:PutObject'
                - 's3:PutObjectAcl'
                - 's3:DeleteObject'
                - 's3:DeleteObjectAcl'
                - 's3:DeleteObjectVersion'
              Resource:
                - 'arn:aws:s3:::s3.codiy.net/*'
                - 'arn:aws:s3:::s3.codiy.net'
  # ----------------------- Backup -----------------------
  Backup:
    Type: AWS::IAM::User
    Properties:
      UserName: backup
      Path: /
      Policies:
        - PolicyName: KfcBackupPolicy
          PolicyDocument:
            Statement:
            - Sid: AllowListBuckets
              Effect: Allow
              Action:
                - 's3:ListAllMyBuckets'
              Resource: 'arn:aws:s3:::*'
            - Sid: AllowManageBucketObjects
              Effect: Allow
              Action:
                - 's3:ListBucket'
                - 's3:GetBucketLocation'
                - 's3:GetObject'
                - 's3:GetObjectAcl'
                - 's3:GetObjectVersion'
                - 's3:PutObject'
                - 's3:PutObjectAcl'
                - 's3:DeleteObject'
                - 's3:DeleteObjectAcl'
                - 's3:DeleteObjectVersion'
              Resource:
                - 'arn:aws:s3:::kfc.backup/*'
                - 'arn:aws:s3:::kfc.backup'
  # ----------------------- Storage -----------------------
  Storage:
    Type: AWS::IAM::User
    Properties:
      UserName: storage
      Path: /
      Policies:
        - PolicyName: KfcStoragePolicy
          PolicyDocument:
            Statement:
            - Sid: AllowListBuckets
              Effect: Allow
              Action:
                - 's3:ListAllMyBuckets'
              Resource: 'arn:aws:s3:::*'
            - Sid: AllowManageBucketObjects
              Effect: Allow
              Action:
                - 's3:ListBucket'
                - 's3:GetBucketLocation'
                - 's3:GetObject'
                - 's3:GetObjectAcl'
                - 's3:GetObjectVersion'
                - 's3:PutObject'
                - 's3:PutObjectAcl'
                - 's3:DeleteObject'
                - 's3:DeleteObjectAcl'
                - 's3:DeleteObjectVersion'
              Resource:
                - 'arn:aws:s3:::kfc.storage/*'
                - 'arn:aws:s3:::kfc.storage'
  # ----------------------- Crazy -----------------------
  Crazy:
    Type: AWS::IAM::User
    Properties:
      UserName: crazy
      Path: /
      Policies:
        - PolicyName: Route53Policy
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 'route53:ListResourceRecordSets'
                - 'route53:GetChange'
                - 'route53:ChangeResourceRecordSets'
              Resource:
                - 'arn:aws:route53:::hostedzone/*'
                - 'arn:aws:route53:::change/*'
            - Effect: Allow
              Action:
                - 'route53:ListHostedZonesByName'
                - 'route53:ListHostedZones'
              Resource: '*'
        - PolicyName: CloudfrontPolicy
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 'acm:ListCertificates'
                - 'cloudfront:AssociateAlias'
                - 'cloudfront:ListTagsForResource'
                - 'cloudfront:GetDistribution'
                - 'cloudfront:CreateDistribution'
                - 'cloudfront:UpdateDistribution'
                - 'cloudfront:GetDistributionConfig'
                - 'cloudfront:TagResource'
                - 'cloudfront:*CachePolicy'
                - 'cloudfront:*OriginRequestPolicy'
                - 'cloudfront:*ResponseHeadersPolicy'
              Resource: '*'
        - PolicyName: CloudFormationPolicy
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - 'cloudformation:CreateStack'
                - 'cloudformation:UpdateStack'
                - 'cloudformation:CreateChangeSet'
                - 'cloudformation:ExecuteChangeSet'
                - 'cloudformation:DescribeChangeSet'
                - 'cloudformation:DeleteChangeSet'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DescribeStackResource'
                - 'cloudformation:GetTemplate'
                - 'cloudformation:ValidateTemplate'
              Resource:
                - !Sub 'arn:aws:cloudformation:us-east-1:${AWS::AccountId}:stack/crazy-*'

