---
- name:
  hosts: localhost
  gather_facts: False
  tasks:

    - set_fact:
        region: ap-southeast-1
        stack_name: cdn-s3-codiy-net
        cfn_template_ansible: ../templates/cfn-cloudfront.yml

    - set_fact:
        alias: s3.codiy.net
        policy_suffix: S3CodiyNet

    - include_tasks: ./tasks/stack.yml
