---
- name:
  hosts: localhost
  gather_facts: False
  tasks:

    - set_fact:
        region: us-east-1
        stack_name: code-commit
        cfn_template_ansible: ../templates/cfn-codecommit.yml

    - include_tasks: ./tasks/stack.yml
