---
AWSTemplateFormatVersion: '2010-09-09'
Description: buckets

Resources:

  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: {{ bucket_name }}
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: Remove Old Incomplete Multipart Upload
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 3
          - Id: Auto-Trans
            Status: Enabled
            Transitions:
              - TransitionInDays: 3
                StorageClass: INTELLIGENT_TIERING

  # ResourceBucketPolicy:
  #   Type: 'AWS::S3::BucketPolicy'
  #   Properties:
  #     Bucket: !Ref 'BackupBucket'
  #     PolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #       - Effect: Allow
  #         Principal:
  #           Service: 'cloudfront.amazonaws.com'
  #         Action: 's3:*'
  #         Resource: !Sub 'arn:aws:s3:::${BackupBucket}/*'
  #         Condition:
  #           StringEquals:
  #             AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/E7XYZJXDBH60N'
