---
AWSTemplateFormatVersion: '2010-09-09'
Description: buckets

Resources:

  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: {{ bucket_name }}
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: Remove Old Incomplete Multipart Upload
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 3
          - Id: Auto-Trans
            Status: Enabled
            Transitions:
              - TransitionInDays: 3
                StorageClass: GLACIER_IR
