---
AWSTemplateFormatVersion: '2010-09-09'
Description: buckets

Resources:

  ResourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: {{ bucket_name }}
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['Authorization', '*']
            AllowedMethods: [GET, POST, PUT, HEAD]
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - ETag
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: Remove Old Incomplete Multipart Upload
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 3
          - Id: Remove Old Thumbnails
            Status: Enabled
            Prefix: _optimized/_thumbnail
            ExpirationInDays: 3
            NoncurrentVersionExpirationInDays: 3
          - Id: Auto Transition
            Status: Enabled
            Transitions:
              - TransitionInDays: 7
                StorageClass: INTELLIGENT_TIERING

  ResourceBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref 'ResourceBucket'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'cloudfront.amazonaws.com'
          Action: 's3:GetObject'
          Resource: !Sub 'arn:aws:s3:::${ResourceBucket}/*'
          Condition:
            StringEquals:
              AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/E12P4WIM1DMOG9'
        - Effect: Allow
          Principal:
            Service: 'cloudfront.amazonaws.com'
          Action: 's3:GetObject'
          Resource: !Sub 'arn:aws:s3:::${ResourceBucket}/*'
          Condition:
            StringEquals:
              AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/E2YO3L8YAD06WW'
        - Effect: Allow
          Principal:
            AWS:
              - !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaRole-us-east-1-func-cdn-image-resize-origin-response'
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - !Sub 'arn:aws:s3:::${ResourceBucket}/_optimized/*'
        - Effect: Allow
          Principal:
            AWS:
              - !Sub 'arn:aws:iam::${AWS::AccountId}:role/lambda-dict-query-LambdaFunctionRole-V0PJT4VW3S0O'
          Action:
            - 's3:GetObject*'
            - 's3:PutObject*'
          Resource:
            - !Sub 'arn:aws:s3:::${ResourceBucket}/dictionary/*'
