---
- name:
  hosts: localhost
  gather_facts: False
  tasks:

    - set_fact:
        region: ap-southeast-1
        stack_name: sns-alarm
        cfn_template_ansible: ../templates/cfn-sns-alarm.yml

    - set_fact:
        subscription_lambda_arn: 'arn:aws:lambda:us-east-1:146617882894:function:func-alarm-sns-dingtalk'

    - include_tasks: ../tasks/stack.yml
