---
- name:
  hosts: localhost
  gather_facts: False
  tasks:

    - set_fact:
        region: us-east-1
        stack_name: cert-cloudfront-codiy-net
        cfn_template_ansible: ../templates/cfn-cert.yml

    - include_tasks: ../tasks/stack.yml
