---
- name:
  hosts: localhost
  gather_facts: False
  tasks:

    - set_fact:
        region: us-east-1
        stack_name: s3-backup
        cfn_template_ansible: ../templates/cfn-s3-backup.yml

    - set_fact:
        bucket_name: kfc.backup

    - include_tasks: ../tasks/stack.yml
